global using Asp.Versioning;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using OrganixMessenger.Controllers.Util;
global using OrganixMessenger.Shared;
global using OrganixMessenger.Shared.API.Requests;
global using OrganixMessenger.Shared.API.Responses;
global using System.Text.Json;
global using OrganixMessenger.Documentation.ReDoc;
global using NSwag.Annotations;
global using System.Net;
global using System.Text.Json.Serialization;
global using System.Text.Encodings.Web;
global using Microsoft.AspNetCore.RateLimiting;
global using OrganixMessenger.ServerServices.JWTTokenGeneratorServices;
global using OrganixMessenger.ServerServices.UserAuthenticationManagerServices;
global using OrganixMessenger.ServerServices.FileHostServices;
global using OrganixMessenger.ServerServices.Repositories.FileRepositories;
global using Microsoft.AspNetCore.Authorization;
global using System.Security.Claims;
global using OrganixMessenger.ServerServices.Repositories.UserRepositories;

return 0;