global using System.Linq.Expressions;
global using Xunit;
global using Moq;
global using OrganixMessenger.ServerServices.EmailServices;
global using OrganixMessenger.ServerServices.HttpContextServices;
global using OrganixMessenger.ServerServices.Repositories.UserRepositories;
global using OrganixMessenger.Shared;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using OrganixMessenger.ServerConfigurations;
global using OrganixMessenger.ServerModels.RefreshTokenModel;
global using OrganixMessenger.ServerServices.Repositories.RefreshTokenRepositories;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using OrganixMessenger.ServerServices.Repositories;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using OrganixMessenger.Controllers.v1;
global using OrganixMessenger.ServerServices.UserAuthenticationManagerServices;
global using OrganixMessenger.Shared.API.Requests;
global using System.Net;
global using OrganixMessenger.Shared.API.Responses;
global using OrganixMessenger.ServerServices.JWTTokenGeneratorServices;
global using OrganixMessenger.ServerTests.Mocks;
global using OrganixMessenger.ServerModels.MessengerEntityModels.ApplicationUserModel;


